### ISSUE TITLE
does this plugin remove nades chat messages ? 

### ISSUE THREAD

**Issue by mayersgamer** [KillStr3aK/IgnoreMessages#2] opened 2024-09-25 19:40 UTC
does this plugin remove nades chat messages ?

**Comment by KillStr3aK** [comment] 2024-09-26 22:45
You can search for those texts in the language file, if they have a key then this plugin **can** remove them

**Comment by mayersgamer** [comment] 2024-09-27 07:23
i think the plugin is broken 
![image](https://github.com/user-attachments/assets/1cb2f18b-d9bd-4d1a-8254-07f53c702994)

**Comment by KillStr3aK** [comment] 2024-09-30 00:42
> i think the plugin is broken (image)
Its known that there is an issue within the core that makes strings gibberish, this has to be fixed in the core itself and not in the plugin as it works as intended

**Closed by KillStr3aK** 2024-09-30 00:42 UTC
